# Generated by Django 5.1.4 on 2025-12-15 01:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        ('project', '0004_remove_projectmembership_access_project_access_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Sprint Name'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='unique_sprint_project'),
        ),
    ]
