# Generated by Django 5.1.4 on 2025-12-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectmembership_project_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembership',
            name='access',
        ),
        migrations.AddField(
            model_name='project',
            name='access',
            field=models.CharField(choices=[('private', 'Private'), ('limited', 'Limited'), ('open', 'Open')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
